---
- hosts: all
  any_errors_fatal: true
  remote_user: centos
  connection: ssh
  vars:
    new_datadog_api_key: null
  vars_prompt:
    - name: "shard_allocation_disabled"
      prompt: "Have you disabled shard allocation? (yes to advance, be honest!)"
      default: "no"
  tasks:
    - name: conditional fail
      fail:
        msg: "Disable shard allocation!"
      run_once: true
      when: shard_allocation_disabled != "yes"
    - name: (data node) set ES_HEAP_SIZE in /etc/sysconfig
      replace:
        dest: /etc/sysconfig/elasticsearch
        regexp: "^#ES_HEAP_SIZE=2g"
        replace: "ES_HEAP_SIZE=14g"
      become: true
      become_user: root
      register: set_es_heap_size
    - include: ../tasks/enable_es_http_api.yml
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
      become: true
      become_user: root
      when: >
        set_es_heap_size.changed == true
    - include: ../tasks/replace_datadog_api_key.yml
    - include: ../tasks/create_elastic_yml.yml
    - include: ../tasks/set_es_node_datadog_tags.yml
