---
- hosts: all
  remote_user: centos
  connection: ssh
  vars:
    new_datadog_api_key: null
  tasks:
    - name: substitute old datadog API key for new key
      replace:
        dest: /etc/dd-agent/datadog.conf
        regexp: "^api_key: [a-zA-Z0-9]*$"
        replace: "api_key: {{new_datadog_api_key}}"
      become: true
      become_user: root
    - name: create /etc/dd-agent/conf.d/elastic.yaml if it does not exist
      copy:
        src: /etc/dd-agent/conf.d/elastic.yaml.example
        dest: /etc/dd-agent/conf.d/elastic.yaml
        remote_src: True
      become: true
      become_user: root
    - name: restart datadog
      service:
        name: datadog-agent
        state: restarted
      become: true
      become_user: root
