---
- hosts: all
  remote_user: centos
  connection: ssh
  vars:
    new_datadog_api_key: null
  tasks:
    - include: ../tasks/replace_datadog_api_key.yml
    - include: ../tasks/create_elastic_yml.yml
    - include: ../tasks/set_es_node_datadog_tags.yml
